base_url = "damienstanton.com"
title = "damienstanton.com"
compile_sass = true
highlight_code = true
build_search_index = true
check_external_links = true

taxonomies = [
    {name = "topics", rss = true}
]

[extra]
show_word_count = true
show_reading_time = true
date_format = "%a %b %e, %Y"
home = "home"
sam_menu = [
    { text = "ğŸ“š words", link = "/words" },
    { text = "ğŸ‘‹ about", link = "/about" },
    { text = "âŒ¨ï¸ code", link = "https://github.com/damienstanton" },
    { text = "ğŸ¦ tweets", link = "https://twitter.com/damienstanton" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = "Copyright Â©ï¸ 2020 Damien Stanton"
